################################# Default configuration ###################
baseURL = "/"
title = "Matthew Jamison - Full-Stack Developer"
theme = "meghna"
# Default time zone for time stamps
timeZone = "America/Chicago"
# post pagination
pagination.pagerSize = 6
# post excerpt
summaryLength = 15
# multilingual support enabled (5 languages: en, es, ja, fr, de)
disableLanguages = []
hasCJKLanguage = true

############################# Build ##############################
[build]
noJSConfigInAssets = false
useResourceCacheWhen = 'fallback'
[build.buildStats]
enable = true
[[build.cachebusters]]
source = 'assets/.*\.(js|ts|jsx|tsx)'
target = '(js|scripts|javascript)'
[[build.cachebusters]]
source = 'assets/.*\.(css|sass|scss)$'
target = '(css|styles|scss|sass)'
[[build.cachebusters]]
source = 'assets/.*\.(.*)$'
target = '$1'

############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS"]
page = ["HTML"]

############################# Imaging ##############################
[imaging]
quality = 90
resampleFilter = "lanczos"

############################# Caches ###############################
[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"

############################# Markup ###############################
[markup]
[markup.goldmark.renderer]
unsafe = true

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"

############################# Default Parameters ##########################
[params]
logo = "images/logo.png"
# Meta data
description = "Full-stack developer delivering measurable ROI: 98+ Lighthouse scores, $6k/year hosting savings, 79% faster load times. Rails • Python • Hugo • AI Tooling. Conversion-optimized development for real business results."
author = "Matthew Jamison"
# Google Analytics (add your tracking ID when ready)
google_analytics_id = ""
# post share
post_share = true

# preloader
[params.preloader]
enable = false
preloader = "images/logo.png"

# cookies
[params.cookies]
enable = false
expire_days = 2

# google map (disabled for now)
[params.map]
enable = false

############################# social icons ##########################
[[params.social]]
icon = "ti-github"
link = "https://github.com/MatthewJamisonJS"

[[params.social]]
icon = "ti-linkedin"
link = "https://www.linkedin.com/in/matthew-jamison-65486bab/"

[[params.social]]
icon = "ti-music"
link = "https://matthewjjamison.bandcamp.com/"

################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1

[Languages.en.params]
home = "Home"
copyright = "Copyright &copy; 2025 Matthew Jamison"

################################ Spanish Language ########################
[Languages.es]
languageName = "Español"
languageCode = "es-es"
contentDir = "content/spanish"
weight = 2

[Languages.es.params]
home = "Inicio"
copyright = "Copyright &copy; 2025 Matthew Jamison"

################################ Japanese Language #######################
[Languages.ja]
languageName = "日本語"
languageCode = "ja-jp"
contentDir = "content/japanese"
weight = 3

[Languages.ja.params]
home = "ホーム"
copyright = "Copyright &copy; 2025 Matthew Jamison"

################################ French Language #########################
[Languages.fr]
languageName = "Français"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 4

[Languages.fr.params]
home = "Accueil"
copyright = "Copyright &copy; 2025 Matthew Jamison"

################################ German Language #########################
[Languages.de]
languageName = "Deutsch"
languageCode = "de-de"
contentDir = "content/german"
weight = 5

[Languages.de.params]
home = "Startseite"
copyright = "Copyright &copy; 2025 Matthew Jamison"

############################# Navigation Menu ##########################
